#!/bin/sh
# shadowsocks-client service

DAEMON='/usr/local/bin/node'
OPTS='/usr/local/bin/sslocal -c /gfwbreakers/transparent/shadowsocks-client/config.json'
USER='root'

start() {
    echo "Starting shadowsocks-client..."
    if [ -x $DAEMON ]; then
        start-stop-daemon -b -o -c $USER -S -u $USER -x $DAEMON -- $OPTS
    fi
}

stop() {
    echo "Stopping shadowsocks-client..."
    if [ -x $DAEMON ]; then
        start-stop-daemon -o -c $USER -K -u $USER -x $DAEMON -- $OPTS
        sleep 5
    fi
}

status() {
    dbpid=`pgrep -u $USER node`
    if [ -z $dbpid ]; then
        echo "shadowsocks-client is not running."
    else
        echo "shadowsocks-client is running with pid $dbpid."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload|force-reload)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/shadowsocks-client {start|stop|reload|force-reload|restart|status}"
        exit 1
esac

exit 0
