#!/bin/sh
# ssh-D socks proxy service

DAEMON='/usr/bin/autossh'
OPTS='autossh -M20000 -q -N -D 8965 -g *@******.***'
USER='root'

start() {
    echo "Starting ssh-d..."
    if [ -x $DAEMON ]; then
        start-stop-daemon -b -o -c $USER -S -u $USER -x $DAEMON -- $OPTS
    fi
}

stop() {
    echo "Stopping ssh-d..."
    if [ -x $DAEMON ]; then
        start-stop-daemon -o -c $USER -K -u $USER -x $DAEMON -- $OPTS
    fi
}

status() {
    dbpid=`pgrep -u $USER autossh`
    if [ -z $dbpid ]; then
        echo "ssh-d is not running."
    else
        echo "ssh-d is running with pid $dbpid."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload|force-reload)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/ssh-d {start|stop|reload|force-reload|restart|status}"
        exit 1
esac

exit 0
